---
######
# Generic configuration. No ERB allowed here!
######

server:
  port: 55345
client:
  required_version: 2012-0122-2012
control:
  token: "u8943hgf238huin&*%Tgbuyb67532fuybvyu3cg6FV#&@GV*IUI@#}234U(**UBCU{bbsjdgbaijgbdasc}"
  # %s will be replaced by Galaxy#callback_url
  web_url: "http://%s/manage"
